# Site settings
encoding: utf-8
title: SteveJokes
description: SteveJokes的个人博客
baseurl: "https://stevejokes.github.io" 
# baseurl: ''
github_username:  SteveJokes
paginate: 8
paginate_path: "/page:num"
footer_twitter: "Twitter"
footer_twitter_site: "https://twitter.com/stevejokes"
footer_github: "GitHub"
footer_resume: "简历"
footer_resume_site: "https://stevejokes.github.io/aboutme/index.html"
port: 8070
gems: [jekyll-paginate]
